version: '3.8'
services:
  backoffice:
    image: scalizup-cons
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_DATABASE=dts
      - ORIGIN=http://localhost:3000
networks:
  default:
    external:
      name: internal-scalizup
