version: '3.8'
services:
  backoffice:
    image: ghcr.io/eduardscript/backoffice
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_DATABASE=dts
      - ORIGIN=https://scalizup.com
networks:
  default:
    external:
      name: internal-scalizup
